# Generated by Django 2.2.5 on 2025-05-26 13:51

from django.db import migrations, models
# -- import the backport
from django2_postgres import operations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]
# -- The concurrent index creation can be only in non-atomic migration
    atomic = False

    operations = [
# -- We remove the originally generated operation ...
#        migrations.AddIndex(
#            model_name='mymodel',
#            index=models.Index(fields=['field1', 'field2'], name='my_index'),
#        ),
# -- And replace it by a modified one
        operations.AddIndexConcurrently(
            model_name='mymodel',
            index=models.Index(fields=['field1', 'field2'], name='my_index'),
        ),
    ]
