# Generated by Django 2.2.5 on 2025-05-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_remove_index_concurrently'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=10)),
                ('field2', models.CharField(max_length=10)),
            ],
        ),
    ]
